services:
  mysql11:
    image: "mariadb:11.4"
    ports:
      - "3306:3306"
    env_file: ".env.mysql"
    volumes:
      - "mysql11_data:/var/lib/mysql"
  flatbacks:
    image: "ghcr.io/dbca-wa/flatbacks-website"
    env_file: ".env.flatbacks"
    volumes:
      - "flatbacks_site:/opt/drupal/web:ro"
      - "${PWD}/settings.php:/opt/drupal/web/sites/default/settings.php:ro"
      - "flatbacks_files:/opt/drupal/web/sites/default/files"
  nginx:
    image: "nginxinc/nginx-unprivileged:stable-alpine"
    ports:
      - "8080:8080"
    environment:
      TZ: "Australia/Perth"
    volumes:
      - "${PWD}/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "flatbacks_site:/var/www/html:ro"
      - "flatbacks_files:/var/www/html/sites/default/files:ro"
  redis:
    image: "redis:7.2-alpine"
    ports:
      - "6379:6379"
    environment:
      TZ: "Australia/Perth"

volumes:
  mysql11_data:
  flatbacks_site:
  flatbacks_files:
