<?php

/**
 * @file
 * Custom module to remove Drupal's Generator meta tag.
 */

/**
 * Implements remove_generator_page_attachments_alter().
 */
function remove_generator_page_attachments_alter(array &$attachments)
{
    if (empty($attachments['#attached']['html_head'])) {
        return;
    }

    foreach ($attachments['#attached']['html_head'] as $key => $element) {
        if (
            isset($element[0]['#attributes']['name'])
            && strtolower($element[0]['#attributes']['name']) === 'generator'
        ) {
            unset($attachments['#attached']['html_head'][$key]);
        }
    }
}
