apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -prod
resources:
  - ../../base
  - ingress.yaml
  - pvc.yaml
secretGenerator:
  - name: flatbacks-env
    type: Opaque
    envs:
      - .env
configMapGenerator:
  - name: flatbacks-configmap
    files:
      - default.conf
      - ports.conf
      - settings.php
      - php-config.ini
generatorOptions:
  disableNameSuffixHash: true
labels:
  - includeSelectors: true
    pairs:
      variant: prod
patches:
  - path: deployment_patch.yaml
  - path: service_patch.yaml
images:
  - name: ghcr.io/dbca-wa/flatbacks-website
    newTag: 10.4.0
