apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flatbacks-files
spec:
  storageClassName: azurefile-csi-retain-zrs
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 4Gi
