apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: blob.csi.azure.com
  name: pv-dbcaturtlesmedia-files-blob
spec:
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteMany
  storageClassName: azureblob-fuse-premium-retain
  mountOptions:
    - -o allow_other
    - --file-cache-timeout-in-seconds=120
  csi:
    driver: blob.csi.azure.com
    volumeHandle: dbcaturtlesmedia_flatbacks-website-files-prod
    volumeAttributes:
      storageAccount: dbcaturtlesmedia
      containerName: flatbacks-website-files-prod
    nodeStageSecretRef:
      name: dbcaturtlesmedia-storage-secret-prod
      namespace: flatback-turtles
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-flatbacks-files-blob
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 4Gi
  volumeName: pv-dbcaturtlesmedia-files-blob-prod
  storageClassName: azureblob-fuse-premium-retain
